name: bot
on:
  push:
    branches:
      - runner
  schedule:
    - cron: "17 0-10/6 * * *" # every 7:17am and 1:17pm UTC+7
  workflow_dispatch:

jobs:
  runner:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
      DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DEVS: ${{ secrets.DEVS }}
      ENV_ACTION: ${{ secrets.ENV_ACTION }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: runner

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install module
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Process
        run: make

